### ISSUE TITLE
Documentation to-do

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#155]
From @yuvipanda and I's documentation round-up...and in order of priority:

High priority
---
- [x] config.yml schema -> documentation (@choldgraf) #198 
- [x] Create a section on debugging (@choldgraf)  #200 
- [x] Create guidelines + best practices for using Dockerfiles (@yuvipanda) [link](https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html)

Medium Priority
---
- [x] Create a gallery of deployments (data8, paws, binder) (@choldgraf) [link](https://zero-to-jupyterhub.readthedocs.io/en/latest/#resources-from-the-community)
- [x] Create a FAQ / Wiki template for the community to add to (@choldgraf) [link](https://zero-to-jupyterhub.readthedocs.io/en/latest/#resources-from-the-community)
- [x] Add directions for getting content into user directories (e.g. with post-build hooks) @yuvipanda 
- [ ] Add short text for zipping up your jhub and downloading it (@choldgraf)

Long-term priority
---
- [ ] Create a screencast or "official" version of the z2jh talk (@choldgraf and @yuvipanda )

**Comment by consideRatio** [comment]
@choldgraf what does the `Add short text for zipping up your jhub and downloading it` checkbox entry mean?

**Action idea:**
Close this issue, create a new with the screencast part only.

**Comment by choldgraf** [comment]
@consideRatio (sorry for the slow turnaround...I was busy getting married :-D )

the idea there was to provide resources to teach people how to capture their files/notebooks/etc in a JupyterHub and download it locally to their computer if the hub will be shut down. I agree we should close this issue!
