### ISSUE TITLE
Issue triage report

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1810]
## Documentation improvements
- [ ] Documentation on Z2JH configuration to make JupyterHub API requests - [wish reference 1](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/84#issuecomment-680556069), [ref 2](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/550).
- [ ] Documentation of "squishier questions like why you'd want to use it, how it benefits teaching in the classroom, and how to use it most effectively." - [wish reference](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/278#issue-274685539)
- [ ] Docs summarizing NFS insights - [ref1](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/421), [ref2](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/683), [ref3](https://github.com/pangeo-data/pangeo-cloud-federation/issues/654)
- [ ] Meta docs about the authenticator section, to describe our thinking of what we can support in Z2JH for example - [wish reference](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/483)
- [ ] Documentation about information security, is this deployment GDPR compliant for example? [ref 1](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/564).
- [ ] Documentation related to bare metal clusters, such as the need to install metallb and a storage provisioner. [ref 1](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/593#issuecomment-625159138)
- [ ] A `helm` troubleshooting section could be useful [ref 1](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/638).
- [ ] Documentation on how to adjust JupyterHub templates and such in z2jh [ref1](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/691), [ref2](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/705)
- [ ] Document / make a note about scaling limitations in the resource sections [ref1](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/732)
- [ ] Promote the [Used by](https://zero-to-jupyterhub.readthedocs.io/en/latest/community/users-list.html) page [ref1](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/737), and perhaps mention specific [curated deployments](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/738) where users can learn some configuration tricks.

## Maintenance
- [ ] Deprecate whitelist config in favor of allowlist
- [ ] Sustainable configuration of authenticators, where our jupyterhub_config.py section should not need to be kept in sync with the authenticator - [ref1](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/644#issuecomment-703857662), [ref2](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/673)

**Comment by manics** [comment]
Today is awesome!

**Comment by GeorgianaElena** [comment]
:heart_eyes:
