### ISSUE TITLE
Release 2.0.0 todo list

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#2743]
Release blocking work:
- [x] Resolve https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2739
- [x] Release oauthenticator 15.0.0 and bump it here, and ensure we get pyjwt 2.4.0+.
  https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2745
- [x] Release JupyterHub patch version, and bump it here.
  https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2745
- [x] Fix failure to bump the github action jupyterhub/action-k3s-helm from v1 to v2, so we can fix broken CI setup z2jh as well via dependabot
  https://github.com/jupyterhub/action-k3s-helm/issues/44
  https://github.com/jupyterhub/action-k3s-helm/pull/45
  https://github.com/jupyterhub/action-k3s-helm/pull/49
  https://github.com/jupyterhub/action-k3s-helm/issues/53
- [x] Test against k8s 1.24, as k3s 1.24 is out
- [x] Let changelog be part of HTML rendered documentation to make it smooth to link out to configuration reference schema
  (Close #2221)
  #2769
- [x] Update changelog to include merged PRs etc, write changelog text about breaking changes etc
  #2528
  I'm working on it, no blockers but its a large changelog with lots of relevant for this release.

Release meta to reduce work when cutting releases:
- [x] Add automation to re-freeze hub image dependencies via manually triggered workflow
  #2749

**Comment by suraj2410** [comment]
waiting for this release as it will potentially solve many bugs fixed in latest releases (more so in 2.2 versions)

**Comment by ihleonard-c3** [comment]
Any updates on a projected release date? I see only the changelog remaining and we're eagerly looking forward to getting our hands on some of the new features and bug fixes.

**Comment by stubclan** [comment]
any updates? waiting on this

**Comment by consideRatio** [comment]
2.0.0-beta.1 release pipeline running now, should be available in 10-15 minutes!

See the changelog in https://zero-to-jupyterhub.readthedocs.io/en/latest/changelog.html.

**Comment by elferherrera** [comment]
will this release a new helm chart version?
