### ISSUE TITLE
.yaml templates tests

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#624]
@yuvipanda suggested we could add tests based on the `helm template` command that can verify that the `.yaml` looks good. I'm going to have this in mind and keep working on the yaml files to resolve #538. I'm currently a novice on testing in general.

If you want to integrate some template tests go for it! I have a lot ahead of me before I'll start with this.

#### TODO
- [x] Learn about template testing from [kubernetes/charts](https://github.com/kubernetes/charts/tree/master/stable)
- [x] Learn from this [Helm cheatsheet](https://gist.github.com/tuannvm/4e1bcc993f683ee275ed36e67c30ac49#automate-testing--linting) about linting and testing
- [x] Learn more about [kubernetes/charts/test](https://github.com/kubernetes/charts/tree/master/test)
- [x] Learn more about `helm lint`
- [x] Learn more about `helm template`
- [x] Learn more about `yamllint`
- [x] Learn about [kubeval](https://github.com/garethr/kubeval)
- [x] Learn by [watching this video](https://www.youtube.com/watch?v=O8zVTvXMRDQ&index=6&list=PLVt9l4b66d5EjjJ_VBe_5tEiJrAGLsDb-&t=4m00s)
- [x] Learn by [watching this video](https://www.youtube.com/watch?v=RoFKN_TVhNE&index=10&list=PLVt9l4b66d5EjjJ_VBe_5tEiJrAGLsDb-)
- [x] Learn about [kubeval](https://github.com/garethr/kubeval)
- [x] CI with `tools/lint.py`
- [ ] Learn about [helm-unittest](https://github.com/lrills/helm-unittest#related-projects--commands)
- [x] Learn more CircleCI

#### Resources
- [x] Watch talk 3 [Brian Richardson - Managing Environments as a Chart](https://www.youtube.com/watch?v=iHZ2bGLSikE&index=3&t=17m12s&list=PLVt9l4b66d5EjjJ_VBe_5tEiJrAGLsDb-)
- [x] Watch talk 6 [Stef Arnold - Testing and Releasing Charts using Helm and ChartMuseum](https://www.youtube.com/watch?v=O8zVTvXMRDQ&index=6&t=0s&list=PLVt9l4b66d5EjjJ_VBe_5tEiJrAGLsDb-)
- [x] Watch talk 10 [Matt Farina - Testing Lessons Learned from the Community Charts](https://www.youtube.com/watch?v=RoFKN_TVhNE&index=10&t=0s&list=PLVt9l4b66d5EjjJ_VBe_5tEiJrAGLsDb-)

**Comment by consideRatio** [comment]
Closed by #844
