### ISSUE TITLE
Cloud provider - Tracking of node-pool support

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#803]
I was considering if it would make sense to make our deployment require a setup where user pods always schedule on user nodes but concluded there was too little support for that among the cloud providers to be able to label nodes from a node pool.

If you know if a cloud provider supports systematic adding of Kubernetes labels to nodes, please let me know. I'm mainly familiar with Google Clouds managed Kubernetes engine (GKE).

#### Google GKE - managed Kubernetes:
- [x] Multiple node pools
- [x] Node pool kubernetes labeling

#### Azure AKS - managed Kubernetes:
- [x] Multiple node pools - https://github.com/Azure/AKS/issues/287
- [ ] Node pool kubernetes labeling (UNKNOWN)

#### Amazon AWS:
- [ ] Multiple node pools (UNKNOWN)
- [ ] Node pool kubernetes labeling (UNKNOWN)

#### Amazon EKS - managed Kubernetes.
- [x] Multiple node pools
- [ ] Node pool kubernetes labeling (UNKNOWN)

**Comment by consideRatio** [comment]
https://blog.hasura.io/gke-vs-aks-vs-eks-411f080640dc

**Comment by ablekh** [comment]
@manics Are you sure? Unless I'm missing something, it seems that the support for node labels is there ... https://github.com/kubernetes-incubator/kubespray/issues/2843

**Comment by manics** [comment]
@ablekh Thanks, I wasn't aware of that. I don't remember seeing it in the Kubespray docs.

**Comment by ablekh** [comment]
@manics My pleasure. Note emphasis that support is unofficial, which explains why docs don't mention it.

**Comment by sgibson91** [comment]
Hi @consideRatio what's the difference between asking the Cloud provider to add Kubernetes labels and using `kubectl label nodes ...`? Or is this more about adding the label to new nodes as they are spun up?

I've been looking into [these docs](https://zero-to-jupyterhub.readthedocs.io/en/latest/optimization.html#efficient-cluster-autoscaling) today for an Azure-based BinderHub deployment and trying to unpick what I need to do.

Thanks!

**Comment by consideRatio** [comment]
Hi @sgibson91, after the label is added there is no difference i think.

But, although i lack some understanding, i know that if you have a cluster autosscaler (CA) that would add nodes when needed because pods are unschedulable, a difference can arise.

If the CA require a node with a certain label to be able to schedule the pod it wants to make room for, if that only is to be added manually later, we have a problem. Then the CA wont attempt to add a node at all as it believes no node options would allow the pod to be scheduled no matter what.

related in k8s pod specification: node affinity / node selector

**Comment by sgibson91** [comment]
Thanks for the reply @consideRatio 

My current idea for an Azure workaround is to label my current 3 nodes as system nodes and accordingly label the binderhub pods to stick to those nodes. Then allow new nodes and user pods to do what they like. Hopefully that will prevent a "undisruptable" pod ending up on a node that then can't be spun down.

**Comment by sgibson91** [comment]
Btw, looks like Azure have added some nodepool commands to their CLI!
https://docs.microsoft.com/en-us/cli/azure/ext/aks-preview/aks/nodepool?view=azure-cli-latest

**Comment by ablekh** [comment]
Hey @consideRatio, Happy New Year! :-) Just wanted to let you know that Azure AKS now supports (GA) multiple node pools (AKS ticket 287 is Resolved and relevant documentation is here: https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools). As for the second item, it is not clear to me whether this feature is GA in AKS or not: on one hand, see https://docs.microsoft.com/en-us/azure/aks/operator-best-practices-advanced-scheduler and https://github.com/Azure/aks-engine/tree/master/examples/kubernetes-labels, on another hand, the following ticket is still open: https://github.com/Azure/AKS/issues/1088 (let me know what you think). Hope this helps.

P.S. 1) Could you point me to some examples of public repos, containing full CI/CD-enabled setup for deployment of a Z2JH cluster; 2) are you aware of any efforts for JH usage metrics collection for billing / accounting purposes?

**Comment by sgibson91** [comment]
I have some notes on setting up AKS for multiple node pools here: https://alan-turing-institute.github.io/hub23-deploy/deploy-k8s-cluster-multiple-nodepools/
I'll put it on my todo list to add to the repo

**Comment by ablekh** [comment]
@sgibson91 Thank you for the link to your notes - I took a quick preliminary look. I was a bit surprised to see the VNET portion (and I know that official Z2JH documentation contains the same instructions - was surprised as well) - when I was deploying our cluster(s) last year, if I remember correctly I was not performing manually any VNET steps and the Z2JH docs did not contain relevant section (I was under impression that AKS configures VNET / network policies by default).

By the way, do you deploy your JH cluster(s) manually or in an automated (CI/CD) fashion?

**Comment by sgibson91** [comment]
So I deploy BinderHub (which has a JupyterHub under the hood and uses this chart) and we discovered recently that if you don't do the VNET steps, then the network policies provided by BinderHub to restrict traffic into the pods aren't obeyed (people could ssh into the JupyterHub when they shouldn't be able to). This is because AKS does not provide a kubernetes controller by default, more details here: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1526 and here: https://github.com/jupyterhub/mybinder.org-deploy/issues/1154

I deploy manually but use an Azure pipeline to upgrade the helm chart: https://github.com/alan-turing-institute/hub23-deploy/blob/master/azure-pipelines.yml
using a bot to manage my chart dependencies: https://github.com/HelmUpgradeBot/hub23-deploy-upgrades

I also developed this repo automatically deploying a BinderHub, but could be modded for JupyterHub: https://github.com/alan-turing-institute/binderhub-deploy
And a colleague made a similar repo for the Littlest JupyterHub: https://github.com/trallard/TLJH-azure-button

**Comment by ablekh** [comment]
@sgibson91 I very much appreciate your clarifications and links. Will review your excellent content at my earliest convenience. Should you learn of any projects or efforts focused on JupyterHub usage metrics collection for billing / accounting purposes, please let me know (hopefully, @consideRatio will chime in on the subject as well).

**Comment by consideRatio** [comment]
Happy new year @ablekh! :D

Thanks for chiming in @sgibson91!

I have only worked on the public CI testing of z2jh. I have not automated the company pricate deployment i manage yet to be managed fully by gitops. Adding that complexity is a tradeoff, and would also cost development time that i have not yet opted to invest in.

Regarding metrics, im working on that now for the first time. I'm learning from the mybinder.org-deploy repo. I could ask my boss if i could spend some time to write about this setup publically. But, in short this is a prometheus/grafana combo based on the prometheus helm chart in helm/stable and the grafana helm chart that has migrated to their own helm chart registry. jupyterhub 1.1.0 has a nice /hub/metrics endpoint that has been tested to work a lot better now than in 1.0.0. I have lots to learn in this domain still. Logs/Metrics/Tracing is a beast of complexity in practice

**Comment by ablekh** [comment]
@consideRatio Thank you! :-)

I appreciate your clarifications. Should you have anything public on the CI/CD aspect (content kindly shared by @sgibson91 is unquestionably very helpful -- again, many thanks to her! - but, in this case, the more, the merrier ...) as well as on the metrics / billing / accounting aspect, please let me know.

**Comment by consideRatio** [comment]
I've lost track of this, but I'll now close it as outdated.
