### ISSUE TITLE
Discussion of Parts of #758 PRs

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#934]
There are some PRs out representing parts of several months work available for review now. In this issue I'd like to discuss those in a one single spot to keep track of the discussion better.

## Concerns
1. **Helm template helpers are hard to read**
   Further usage should be avoided and the DRY principle is reasonable to compromise on in order to do it.
2. **Deviations from Kubernetes API**
   We should attempt to use the exact same field names as kubernetes within our configuration options. Not doing this leads to additional documentation requirements and additional work mapping from our naming to their naming.
3. **How to deprecate configuration?**
   The best idea I have is to use `NOTES.txt` and warn users based on utilizing anything being deprecated. `NOTES.txt` will render whenever the user is making an upgrade or installs something, which makes it perfect for warnings.

## Introduction to challenges
1. **Helm templates have a limited toolbox**
   In a Helm template, can you only do certain things. I realize that it may be possible but I had not realized it now, that one may be able to write `.Values.some.nested.value`

2. **Helm templates + `jupyterhub_config.py`**
   A lot of the things we do need to be done twice or sometimes even more times using different tools: Helm templates toolbox and once using python code running in `jupyterhub_config.py`. When this is the case. I've often attempted to do the work using the Helm toolbox, and then let `jupyterhub_config.py` import the processed stuff.

3. **Helper scopes**
   Every value you can access in a Helm template resides in the `.` dictionary called the current scope, example values you can access are `.Values.singleuser.image.tag` and `.Release.Name`. If you invoke a Helm template helper function, you will need to pass the helper function its scope. Below are examples on how that can be done, but as you can notice one may want something quite complicated in the end making the code harder to read.
   ```yaml
   # passes the current scope (.)
   {{- include "jupyterhub.myHelperFunction" . }}
   # passes a single string leaving the helper unable to access .Release.Name for example
   {{- include "jupyterhub.myHelperFunction" "my-string-arg" }}
   # passes a dictionary of args, still no access to .Release.Name etc, but multiple arguments
   {{- include "jupyterhub.myHelperFunction" dict "arg1" "val1" "arg2" "val2" }}
   # passes a dict of arguments that is enriched with the values from the current scope (.)
   # this helper will be able to access .arg1 and .Release.Name and .Values.singleuser.image.tag etc.
   {{- $theHelperFunctionsScope := merge (dict "arg1" "val1" "arg2" "val2") . }}
   {{- include "jupyterhub.myHelperFunction" $theHelperFunctionsScope }}
   ```
   I've systematically followed the last implementation strategy even though the helper currently didn't need access to `.Release.Name` for example, as long as the helper required any provided argument.

## Addressing the concerns
I share these concerns with @minrk!

#### Actions to take
- [ ] I can make the `merge` statements more readable I think, for example by doing the following change:
  ```yaml
  # hard to read!
  {{- $_ := merge (dict "podKind" "user") . }}
  {{- include "jupyterhub.prepareScope" $_ }}
  ```
  ```yaml
  # perhaps better enough to motivate a systematic change?
  {{- $args := dict "podKind" "user" }}
  {{- $_ := merge $args . }}
  {{- include "jupyterhub.prepareScope" $_ }}
  ```
  ```yaml
  # I could also change the name of $_ to something more indicative
  # Got a suggestion for a name to replace $_ ?
  # The names: $args, $scope, $helperScope, $augmentedScope are some ideas for example
  {{- $args := dict "podKind" "user" }}
  {{- $currentScopeCopyAugmentedWithArgs := merge $args . }}
  {{- include "jupyterhub.prepareScope" $currentScopeCopyAugmentedWithArgs}}
  ```

- [ ] I can attempt to use the `merge` function with things from `.Values`
  I have made some manual merges that have made me cringe, for example in the helper called `jupyterhub.defaultResources`. It ended up becoming extra complicated due to a deviation from the Kubernetes API in the naming of `guarantees` instead of the Kubernetes API `requests`. I think I may end up needing a `coalesce` function rather than a `merge` function though. The merge function may override too much, but perhaps now.
  Related to this, is also to make sure to utilize [all the functionality](https://godoc.org/github.com/Masterminds/sprig) in the available toolbox.

- [ ] See if I can utilize some tools from the Helm template toolbox such as `pluck` in order to simplify template logic.

### Concern 2 - Deviations from Kubernetes API
It can be hard to augment things both in the helm templates as well.

For example if we would have `singleuser.affinity` and would ask users to follow the Kubernetes API and specify a big nested object that follows ([`affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[]
`](https://github.com/jupyterhub/kubespawner/pull/239#issuecomment-414068391)), and later need to augment or filter out parts of this for various templates. For example regarding augmentation, one may want to augment it with a nodeAffinity of the required kind when we allow users to specify `require` in the matchNodePurpose configuration preset. Another example is that one may want to filter out the affinities that isn't `affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution` as a DaemonSet can't utilize affinity preferences.

#### Actions to take
- [ ] Deprecate `resources.guanratees` in favor of `resources.requests`
  This could reduce the complexity of `jupyterhub.defaultResources` helper by a lot.

---

After writing this, I think we should have a video meeting instead about this. It is simply too time inefficient to write it all. Perhaps we could make an agenda and discuss this in 30 minutes SHARP, allow me to do changes and then have another 30 minutes SHARP video meeting or similar?

**Comment by consideRatio** [comment]
## TODO
- [ ] Split `jupyterhub.affinity` helper into one helper for the user pods and one for the core pods
- [ ] Integrate `jupyterhub.prepareScope`'s in `jupyterhub.affinity` and `jupyterhub.tolerations`
- [ ] Delete Custom specification of resources for `user-placeholder` and `user-dummy`
- [ ] Delete the preset `preferScheduleNextToRealUsers`

**Comment by consideRatio** [comment]
## Challange - While .Values is a dict, a helper's output is text
If you have `.Values.someKey` that can be a dict, list, string etc, but if you would place that in a helper, that would become a string. So, if you want to manipulate the output of the helper, you suddenly need to treat the content as a string without the power to use Dict functions found in the [sprig library](https://godoc.org/github.com/Masterminds/sprig).

**Comment by consideRatio** [comment]
## Challenge - The hub's configmap
All keys under the ConfigMap are mounted as separate files. To avoid too much challenges we should probably have one big file that contains `.Values`. If we want to remove some parts of it, we can do it by first making a copy of .Values, and then stripping things from it using sprig functions like `omit`.

**Comment by consideRatio** [comment]
## Best practice to consider - Store default content in `values.yaml`
If you want to augment a list with YAML text entries representing a list, that can be a bit messy as `.Values` content is typed to different things, while everything in a Helm template is strings.

**Comment by consideRatio** [comment]
## Solutions ?
I'll do my best with the tools I have, which is Helm 2 go templating + sprig functions, which is very restrictive. In the future, with Helm 3, we will be able to do a lot more thanks to the introduction of Lua scripts allowing us to remain typed.

See the **Work on YAML chunks** section in [this article about Helm 3](https://sweetcode.io/a-first-look-at-the-helm-3-plan/) for example to get the discussion from the developers of Helm.

**Comment by consideRatio** [comment]
@minrk I've worked on resolving the stuff in the PRs, it is very hard to reduce complexity at the same time as removing prepareScopes based on:
1. Limitations in helm template functions, resolved with Helm 3's Lua
2. Being forced to passthrough things in the configmap.
  - It has certain keys, and all the content of the keys should be treated as a string to be YAML parsed later by the jupyterhub_config.py script.
  - The keys should not be blank
  - The keys of tolerations should preferably just hold the content of tolerations, not in turn have a "tolerations" entry within it.

**Comment by consideRatio** [comment]
I will make further attempts, the initial step is to:
1. Remove potential easy configuration of the core pods' tolerations.
